name: "バグ報告"
description: "動作の不具合やエラーを報告する"
type: Bug
body:
  - type: markdown
    attributes:
      value: "バグ報告にご協力いただきありがとうございます。"
  - type: textarea
    id: bug-description
    attributes:
      label: "バグの説明"
      description: "バグの内容を具体的に説明してください。"
      placeholder: "発生している問題を明確かつ簡潔に説明してください。"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "再現手順"
      description: "バグを再現するための手順を記載してください。"
      placeholder: |
        1. 「...」に移動する
        2. 「....」をクリックする
        3. 「....」までスクロールする
        4. エラーが表示される
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "期待される動作"
      description: "本来であればどのような動作を期待していましたか？"
      placeholder: "期待していた動作を明確かつ簡潔に説明してください。"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "スクリーンショット"
      description: "可能であれば、問題に関連するスクリーンショットを添付してください。"
  - type: input
    id: os
    attributes:
      label: "OS"
      description: "例: Windows 11, macOS Sonoma 14.2"
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: "ブラウザ"
      description: "例: Chrome 120, Safari 17.2"
    validations:
      required: false
