# Docker Compose override file for Dev Container
# This file extends and customizes the base compose.yml for Dev Container usage.
# It defines the app service that depends on services in ../compose.yml

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
      # Paths are relative to the project root (first compose file location)
      - ./config/dev-secrets.env
    volumes:
      # Mount the project workspace
      # Path is relative to the location of the FIRST docker compose file (../compose.yml in project root)
      # All relative paths in ALL compose files are resolved from the project root directory
      # Therefore, "." refers to the project root directory
      - .:/workspaces/shinju-date:cached
    command: sleep infinity
    environment:
      # Environment variables loaded from env_file (./config/dev-secrets.env):
      # SUPABASE_ANON_KEY, SUPABASE_SERVICE_KEY, NEXT_PUBLIC_SUPABASE_ANON_KEY, UPSTASH_REDIS_REST_TOKEN
      SUPABASE_URL: http://kong:8000
      UPSTASH_REDIS_REST_URL: http://serverless-redis-http:80
      NEXT_PUBLIC_SUPABASE_URL: http://kong:8000
    depends_on:
      serverless-redis-http:
        condition: service_healthy
      kong:
        condition: service_healthy
      db:
        condition: service_healthy
