export { default as appleTouchIcon } from './apple-touch-icon.png'
export { default as favicon192x192 } from './favicon-192x192.png'
export { default as favicon512x512 } from './favicon-512x512.png'
export { default as hero } from './hero.jpg'
export { default as Icon } from './icon.svg'
export { default as Logo } from './logo.svg'
export { default as shareCard } from './share-card.jpg'
